services:
  - type: web
    name: pawpromise-backend
    env: node
    buildCommand: pnpm install --no-frozen-lockfile && pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: pawpromise-backend
          property: port