import { Types } from 'mongoose';
import { lunaId, shadowId, buddyId, whiskersId, maxId } from './pets';

export const sampleHealthRecords = [
  // Luna's records
  {
    _id: new Types.ObjectId(),
    petId: lunaId,
    type: 'vaccination',
    title: 'Annual Vaccination - DHPP',
    description: 'Distemper, Hepatitis, Parvovirus, Parainfluenza vaccination',
    date: new Date('2024-01-15'),
    veterinarian: 'Dr. Emily Johnson',
    clinic: 'City Veterinary Clinic',
    nextDueDate: new Date('2025-01-15'),
    weight: 30.5,
    temperature: 101.2,
    cost: 85.00,
    notes: 'Pet responded well to vaccination. No adverse reactions.',
    isReminder: true,
    isCompleted: false,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: new Types.ObjectId(),
    petId: lunaId,
    type: 'checkup',
    title: 'Annual Health Checkup',
    description: 'Comprehensive physical examination and blood work',
    date: new Date('2024-01-15'),
    veterinarian: 'Dr. Emily Johnson',
    clinic: 'City Veterinary Clinic',
    weight: 30.5,
    temperature: 101.2,
    heartRate: 120,
    cost: 150.00,
    notes: 'Overall health excellent. Recommend dental cleaning next visit.',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: new Types.ObjectId(),
    petId: lunaId,
    type: 'treatment',
    title: 'Ear Infection Treatment',
    description: 'Treatment for bacterial ear infection',
    date: new Date('2023-11-20'),
    veterinarian: 'Dr. Michael Brown',
    clinic: 'City Veterinary Clinic',
    weight: 30.0,
    temperature: 102.1,
    cost: 95.00,
    notes: 'Prescribed antibiotic ear drops. Follow-up in 2 weeks.',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  // Shadow's records
  {
    _id: new Types.ObjectId(),
    petId: shadowId,
    type: 'vaccination',
    title: 'FVRCP Vaccination',
    description: 'Feline Viral Rhinotracheitis, Calicivirus, Panleukopenia',
    date: new Date('2024-02-10'),
    veterinarian: 'Dr. Sarah Wilson',
    clinic: 'Feline Health Center',
    nextDueDate: new Date('2025-02-10'),
    weight: 4.2,
    temperature: 101.8,
    cost: 75.00,
    notes: 'Vaccination completed successfully.',
    isReminder: true,
    isCompleted: false,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: new Types.ObjectId(),
    petId: shadowId,
    type: 'grooming',
    title: 'Professional Grooming',
    description: 'Full grooming service including bath, brush, and nail trim',
    date: new Date('2024-01-05'),
    veterinarian: 'Professional Groomer',
    clinic: 'Pet Spa & Grooming',
    weight: 4.1,
    cost: 60.00,
    notes: 'Coat in excellent condition. No matting found.',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  // Buddy's records
  {
    _id: new Types.ObjectId(),
    petId: buddyId,
    type: 'treatment',
    title: 'Arthritis Management',
    description: 'Joint pain assessment and treatment plan',
    date: new Date('2024-01-20'),
    veterinarian: 'Dr. Robert Davis',
    clinic: 'Senior Pet Care Clinic',
    weight: 35.0,
    temperature: 101.5,
    cost: 180.00,
    notes: 'Started on joint supplements and pain management protocol.',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: new Types.ObjectId(),
    petId: buddyId,
    type: 'checkup',
    title: 'Senior Pet Wellness Exam',
    description: 'Comprehensive senior pet health evaluation',
    date: new Date('2023-12-15'),
    veterinarian: 'Dr. Robert Davis',
    clinic: 'Senior Pet Care Clinic',
    nextDueDate: new Date('2024-06-15'),
    weight: 34.8,
    temperature: 101.3,
    heartRate: 110,
    cost: 200.00,
    notes: 'Arthritis progression noted. Adjusted medication dosage.',
    isReminder: true,
    isCompleted: false,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  }
];

module.exports = { sampleHealthRecords };