import { Types } from 'mongoose';
import { sampleUsers } from './users';

export const samplePets = [
  // Pets for akdavid4real@gmail.com
  {
    _id: new Types.ObjectId(),
    name: 'Luna',
    species: 'dog',
    breed: 'Labrador Retriever',
    age: 2,
    gender: 'female',
    weight: 25.0,
    color: 'Black',
    microchipId: 'MC111222333',
    ownerId: sampleUsers[0]._id,
    dateOfBirth: new Date('2022-05-10'),
    medicalNotes: 'Very active and healthy. Loves swimming.',
    emergencyContactName: 'David Ak',
    emergencyContactPhone: '+1234567890',
    healthStatus: 'healthy',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: new Types.ObjectId(),
    name: 'Shadow',
    species: 'cat',
    breed: 'Maine Coon',
    age: 4,
    gender: 'male',
    weight: 6.5,
    color: 'Gray',
    microchipId: 'MC444555666',
    ownerId: sampleUsers[0]._id,
    dateOfBirth: new Date('2020-08-15'),
    medicalNotes: 'Indoor/outdoor cat. Regular flea prevention.',
    emergencyContactName: 'David Ak',
    emergencyContactPhone: '+1234567890',
    healthStatus: 'healthy',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: new Types.ObjectId(),
    name: 'Buddy',
    species: 'dog',
    breed: 'Golden Retriever',
    age: 3,
    gender: 'male',
    weight: 30.5,
    color: 'Golden',
    microchipId: 'MC123456789',
    ownerId: sampleUsers[1]._id,
    dateOfBirth: new Date('2021-03-15'),
    medicalNotes: 'Allergic to chicken. Prone to hip dysplasia.',
    emergencyContactName: 'Sarah Doe',
    emergencyContactPhone: '+1234567891',
    healthStatus: 'healthy',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: new Types.ObjectId(),
    name: 'Whiskers',
    species: 'cat',
    breed: 'Persian',
    age: 5,
    gender: 'female',
    weight: 4.2,
    color: 'White',
    microchipId: 'MC987654321',
    ownerId: sampleUsers[2]._id,
    dateOfBirth: new Date('2019-07-22'),
    medicalNotes: 'Indoor cat. Regular grooming required.',
    emergencyContactName: 'Mike Smith',
    emergencyContactPhone: '+1987654322',
    healthStatus: 'healthy',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: new Types.ObjectId(),
    name: 'Max',
    species: 'dog',
    breed: 'German Shepherd',
    age: 7,
    gender: 'male',
    weight: 35.0,
    color: 'Black and Tan',
    microchipId: 'MC456789123',
    ownerId: sampleUsers[1]._id,
    dateOfBirth: new Date('2017-01-10'),
    medicalNotes: 'Senior dog. Arthritis in hind legs.',
    emergencyContactName: 'Sarah Doe',
    emergencyContactPhone: '+1234567891',
    healthStatus: 'chronic',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  }
];

module.exports = { samplePets };